name: bank
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/shervin-h/bank
repository: https://github.com/shervin-h/bank
issue_tracker: https://github.com/shervin-h/bank/issues

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
